# Example Home Assistant configuration for Thermostat Setback Controller

# Example schedule for weekday setback
schedule:
  weekday_setback:
    name: "Weekday Setback"
    mode: restart
    actions:
      - service: schedule.turn_on
        data:
          entity_id: schedule.weekday_setback
        time: "22:00:00"
      - service: schedule.turn_off
        data:
          entity_id: schedule.weekday_setback
        time: "06:00:00"

# Example automation to enable setback when away
automation:
  - alias: "Enable Setback When Away"
    description: "Enable setback mode when no one is home"
    trigger:
      - platform: state
        entity_id: person.john
        to: "not_home"
      - platform: state
        entity_id: person.jane
        to: "not_home"
    condition:
      - condition: state
        entity_id: person.john
        state: "not_home"
      - condition: state
        entity_id: person.jane
        state: "not_home"
    action:
      - service: thermostat_setback.set_setback
        target:
          entity_id: thermostat_setback.living_room_controller

  - alias: "Disable Setback When Home"
    description: "Disable setback mode when someone returns home"
    trigger:
      - platform: state
        entity_id: person.john
        to: "home"
      - platform: state
        entity_id: person.jane
        to: "home"
    action:
      - service: thermostat_setback.clear_setback
        target:
          entity_id: thermostat_setback.living_room_controller

# Example script for manual setback control
script:
  enable_setback:
    alias: "Enable Setback Mode"
    sequence:
      - service: thermostat_setback.set_setback
        target:
          entity_id: thermostat_setback.living_room_controller
      - service: notify.mobile_app_phone
        data:
          message: "Setback mode enabled - temperature set to 18°C"

  disable_setback:
    alias: "Disable Setback Mode"
    sequence:
      - service: thermostat_setback.clear_setback
        target:
          entity_id: thermostat_setback.living_room_controller
      - service: notify.mobile_app_phone
        data:
          message: "Setback mode disabled - temperature set to 22°C"

# Example input helpers for dynamic temperature control
input_number:
  setback_temperature:
    name: "Setback Temperature"
    min: 10
    max: 25
    step: 0.5
    unit_of_measurement: "°C"
    initial: 18

  normal_temperature:
    name: "Normal Temperature"
    min: 15
    max: 30
    step: 0.5
    unit_of_measurement: "°C"
    initial: 22

# Example template sensor to show current setback status
template:
  - sensor:
      - name: "Setback Status"
        state: >
          {% if is_state('thermostat_setback.living_room_controller', 'heat') %}
            {% if state_attr('thermostat_setback.living_room_controller', 'is_setback') %}
              Setback Active ({{ state_attr('thermostat_setback.living_room_controller', 'setback_temperature') }}°C)
            {% else %}
              Normal Mode ({{ state_attr('thermostat_setback.living_room_controller', 'normal_temperature') }}°C)
            {% endif %}
          {% else %}
            Off
          {% endif %}
