set_setback:
  name: Set Setback
  description: Manually enable setback mode
  fields:
    entity_id:
      name: Entity
      description: The climate setback entity to control
      selector:
        entity:
          domain: climate_setback

clear_setback:
  name: Clear Setback
  description: Manually disable setback mode
  fields:
    entity_id:
      name: Entity
      description: The climate setback entity to control
      selector:
        entity:
          domain: climate_setback
